FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY web/ ./web

COPY models/ ./models

COPY web/templates/ ./web/templates

COPY web/static/ ./web/static

CMD ["python", "-m", "web.app"]