services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - LOG_LEVEL=${LOG_LEVEL}
      - ADMIN_TELEGRAM_ID=${ADMIN_TELEGRAM_ID}
      - YOKASSA_ACCOUNT_ID=${YOKASSA_ACCOUNT_ID}
      - YOKASSA_SECRET_KEY=${YOKASSA_SECRET_KEY}
      - RUBITIME_API_KEY=${RUBITIME_API_KEY}
      - BOT_LINK=${BOT_LINK}
      - INVITE_LINK=${INVITE_LINK}
      - GROUP_ID=${GROUP_ID}
      - FOR_LOGS=${FOR_LOGS}
    volumes:
      - ./data:/data
      - ./utils:/app/utils
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "test", "-f", "/data/bot_initialized"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    environment:
      - ADMIN_LOGIN=${ADMIN_LOGIN}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - BOT_TOKEN=${BOT_TOKEN}
      - LOG_LEVEL=${LOG_LEVEL}
    ports:
      - "5001:5001"
    volumes:
      - ./data:/data
      - ./utils:/app/utils
      - ./web/static/avatars:/app/static/avatars
    restart: unless-stopped
    depends_on:
      bot:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/login"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s