services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - ADMIN_TELEGRAM_ID=${ADMIN_TELEGRAM_ID}
    volumes:
      - ./data:/data
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    environment:
      - ADMIN_LOGIN=${ADMIN_LOGIN}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    ports:
      - "5001:5001"
    volumes:
      - ./data:/data
    restart: unless-stopped
    depends_on:
      - bot
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/login"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s